package ph.txtdis.app;

import java.time.LocalDate;
import java.util.Arrays;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import ph.txtdis.model.Account;
import ph.txtdis.model.Customer;
import ph.txtdis.model.Location;
import ph.txtdis.model.LocationTree;
import ph.txtdis.model.Route;
import ph.txtdis.model.Routing;
import ph.txtdis.model.SystemUser;
import ph.txtdis.service.AccountService;
import ph.txtdis.service.ChannelService;
import ph.txtdis.service.CustomerService;
import ph.txtdis.service.LocationService;
import ph.txtdis.service.LocationTreeService;
import ph.txtdis.service.RouteService;
import ph.txtdis.service.UserService;
import ph.txtdis.type.CustomerType;
import ph.txtdis.type.LocationType;
import ph.txtdis.type.VisitFrequency;

@Component
public class CustomerSetupImpl implements CustomerSetup {

    @Autowired
    UserService userService;

    @Autowired
    ChannelService channelService;

    @Autowired
    RouteService routeService;

    @Autowired
    AccountService accountService;

    @Autowired
    LocationService locationService;

    @Autowired
    LocationTreeService locationTreeService;

    @Autowired
    CustomerService customerService;

    public CustomerSetupImpl() {
    }

    @Override
    public void start() {

        SystemUser dsp1 = userService.get("OGIE");
        SystemUser dsp2 = userService.get("PHILLIP");
        SystemUser dsp3 = userService.get("BONG");
        SystemUser dsp4 = userService.get("RANDY");
        SystemUser dsp5 = userService.get("ROBERT");
        SystemUser dsp6 = userService.get("HENRY");
        SystemUser dsp7 = userService.get("ROLAND");

        Route s41 = routeService.save(new Route("S41"));
        Route s42 = routeService.save(new Route("S42"));
        Route s43 = routeService.save(new Route("S43"));
        Route s44 = routeService.save(new Route("S44"));
        routeService.save(new Route("S45"));
        Route pms1 = routeService.save(new Route("PMS1"));
        Route pms2 = routeService.save(new Route("PMS2"));
        Route pms3 = routeService.save(new Route("PMS3"));

        LocalDate startDate = LocalDate.parse("2014-07-01");
        accountService.save(new Account(dsp1, s41, startDate));
        accountService.save(new Account(dsp2, s42, startDate));
        accountService.save(new Account(dsp3, s43, startDate));
        accountService.save(new Account(dsp4, s44, startDate));
        accountService.save(new Account(dsp5, pms1, startDate));
        accountService.save(new Account(dsp6, pms2, startDate));
        accountService.save(new Account(dsp7, pms3, startDate));

        Location bulacan = locationService.save(new Location("BULACAN", LocationType.PROVINCE));
        Location san_jose_del_monte = locationService.save(new Location("SAN JOSE DEL MONTE", LocationType.CITY));
        Location assumption = locationService.save(new Location("ASSUMPTION", LocationType.BARANGAY));
        Location bagong_buhay = locationService.save(new Location("BAGONG BUHAY", LocationType.BARANGAY));
        Location citrus = locationService.save(new Location("CITRUS", LocationType.BARANGAY));
        Location ciudad_real = locationService.save(new Location("CIUDAD REAL", LocationType.BARANGAY));
        Location dulong_bayan = locationService.save(new Location("DULONG BAYAN", LocationType.BARANGAY));
        Location fatima = locationService.save(new Location("FATIMA", LocationType.BARANGAY));
        Location francisco_homes = locationService.save(new Location("FRANCISCO HOMES", LocationType.BARANGAY));
        Location gaya_gaya = locationService.save(new Location("GAYA-GAYA", LocationType.BARANGAY));
        Location graceville = locationService.save(new Location("GRACEVILLE", LocationType.BARANGAY));
        Location gumaoc = locationService.save(new Location("GUMAOC", LocationType.BARANGAY));
        Location kaybanban = locationService.save(new Location("KAYBANBAN", LocationType.BARANGAY));
        Location kaypian = locationService.save(new Location("KAYPIAN", LocationType.BARANGAY));
        Location lawang_pare = locationService.save(new Location("LAWANG PARE", LocationType.BARANGAY));
        Location maharlika = locationService.save(new Location("MAHARLIKA", LocationType.BARANGAY));
        Location minuyan = locationService.save(new Location("MINUYAN", LocationType.BARANGAY));
        Location muzon = locationService.save(new Location("MUZON", LocationType.BARANGAY));
        Location paradise = locationService.save(new Location("PARADISE", LocationType.BARANGAY));
        Location poblacion = locationService.save(new Location("POBLACION", LocationType.BARANGAY));
        Location san_isidro = locationService.save(new Location("SAN ISIDRO", LocationType.BARANGAY));
        Location san_manuel = locationService.save(new Location("SAN MANUEL", LocationType.BARANGAY));
        Location san_martin = locationService.save(new Location("SAN MARTIN", LocationType.BARANGAY));
        Location san_pedro = locationService.save(new Location("SAN PEDRO", LocationType.BARANGAY));
        Location san_rafael = locationService.save(new Location("SAN RAFAEL", LocationType.BARANGAY));
        Location san_roque = locationService.save(new Location("SAN ROQUE", LocationType.BARANGAY));
        Location sapang_palay = locationService.save(new Location("SAPANG PALAY", LocationType.BARANGAY));
        Location saint_martin_de_porres = locationService.save(new Location("SAINT MARTIN DE PORRES",
                LocationType.BARANGAY));
        Location santa_cruz = locationService.save(new Location("SANTA CRUZ", LocationType.BARANGAY));
        Location santo_cristo = locationService.save(new Location("SANTO CRISTO", LocationType.BARANGAY));
        Location santo_niño = locationService.save(new Location("SANTO NIÑO", LocationType.BARANGAY));
        Location tungkong_mangga = locationService.save(new Location("TUNGKONG MANGGA", LocationType.BARANGAY));
        Location santa_maria = locationService.save(new Location("SANTA MARIA", LocationType.CITY));
        Location bagbaguin = locationService.save(new Location("BAGBAGUIN", LocationType.BARANGAY));
        Location balasing = locationService.save(new Location("BALASING", LocationType.BARANGAY));
        Location buenavista = locationService.save(new Location("BUENAVISTA", LocationType.BARANGAY));
        Location bulac = locationService.save(new Location("BULAC", LocationType.BARANGAY));
        Location camangyanan = locationService.save(new Location("CAMANGYANAN", LocationType.BARANGAY));
        Location catmon = locationService.save(new Location("CATMON", LocationType.BARANGAY));
        Location caypombo = locationService.save(new Location("CAYPOMBO", LocationType.BARANGAY));
        Location caysio = locationService.save(new Location("CAYSIO", LocationType.BARANGAY));
        Location guyong = locationService.save(new Location("GUYONG", LocationType.BARANGAY));
        Location lalakhan = locationService.save(new Location("LALAKHAN", LocationType.BARANGAY));
        Location mag_asawang_sapa = locationService.save(new Location("MAG-ASAWANG SAPA", LocationType.BARANGAY));
        Location mahabang_parang = locationService.save(new Location("MAHABANG PARANG", LocationType.BARANGAY));
        Location manggahan = locationService.save(new Location("MANGGAHAN", LocationType.BARANGAY));
        Location parada = locationService.save(new Location("PARADA", LocationType.BARANGAY));
        Location pulong_buhangin = locationService.save(new Location("PULONG BUHANGIN", LocationType.BARANGAY));
        Location san_gabriel = locationService.save(new Location("SAN GABRIEL", LocationType.BARANGAY));
        Location san_jose_patag = locationService.save(new Location("SAN JOSE PATAG", LocationType.BARANGAY));
        Location san_vicente = locationService.save(new Location("SAN VICENTE", LocationType.BARANGAY));
        Location santa_clara = locationService.save(new Location("SANTA CLARA", LocationType.BARANGAY));
        Location santo_tomas = locationService.save(new Location("SANTO TOMAS", LocationType.BARANGAY));
        Location silangan = locationService.save(new Location("SILANGAN", LocationType.BARANGAY));
        Location tumana = locationService.save(new Location("TUMANA", LocationType.BARANGAY));

        Location a_mabini = locationService.save(new Location("A. MABINI", LocationType.BARANGAY));
        Location baesa = locationService.save(new Location("BAESA", LocationType.BARANGAY));
        Location bagong_barrio = locationService.save(new Location("BAGONG BARRIO", LocationType.BARANGAY));
        Location barrio_san_jose = locationService.save(new Location("BARRIO SAN JOSE", LocationType.BARANGAY));
        Location biglang_awa = locationService.save(new Location("BIGLANG-AWA", LocationType.BARANGAY));
        Location dagat_dagatan = locationService.save(new Location("DAGAT-DAGATAN", LocationType.BARANGAY));
        Location grace_park_east = locationService.save(new Location("GRACE PARK EAST", LocationType.BARANGAY));
        Location grace_park_west = locationService.save(new Location("GRACE PARK WEST", LocationType.BARANGAY));
        Location heroes_del_96 = locationService.save(new Location("HEROES DEL 96", LocationType.BARANGAY));
        Location kaunlaran_village = locationService.save(new Location("KAUNLARAN VILLAGE", LocationType.BARANGAY));
        Location libis_reparo = locationService.save(new Location("LIBIS REPARO", LocationType.BARANGAY));
        Location maypajo = locationService.save(new Location("MAYPAJO", LocationType.BARANGAY));
        Location monumento = locationService.save(new Location("MONUMENTO", LocationType.BARANGAY));
        Location morning_breeze = locationService.save(new Location("MORNING BREEZE", LocationType.BARANGAY));
        Location sangandaan = locationService.save(new Location("SANGANDAAN", LocationType.BARANGAY));
        Location santa_quiteria = locationService.save(new Location("SANTA QUITERIA", LocationType.BARANGAY));
        Location talipapa = locationService.save(new Location("TALIPAPA", LocationType.BARANGAY));
        Location university_hills = locationService.save(new Location("UNIVERSITY HILLS", LocationType.BARANGAY));
        Location almanza_dos = locationService.save(new Location("ALMANZA DOS", LocationType.BARANGAY));
        Location almanza_uno = locationService.save(new Location("ALMANZA UNO", LocationType.BARANGAY));
        Location caa_bf_international = locationService
                .save(new Location("CAA-BF INTERNATIONAL", LocationType.BARANGAY));
        Location daniel_fajardo = locationService.save(new Location("DANIEL FAJARDO", LocationType.BARANGAY));
        Location elias_aldana = locationService.save(new Location("ELIAS ALDANA", LocationType.BARANGAY));
        Location ilaya = locationService.save(new Location("ILAYA", LocationType.BARANGAY));
        Location manuyo_dos = locationService.save(new Location("MANUYO DOS", LocationType.BARANGAY));
        Location manuyo_uno = locationService.save(new Location("MANUYO UNO", LocationType.BARANGAY));
        Location pamplona_dos = locationService.save(new Location("PAMPLONA DOS", LocationType.BARANGAY));
        Location pamplona_tres = locationService.save(new Location("PAMPLONA TRES", LocationType.BARANGAY));
        Location pamplona_uno = locationService.save(new Location("PAMPLONA UNO", LocationType.BARANGAY));
        Location pilar_village = locationService.save(new Location("PILAR VILLAGE", LocationType.BARANGAY));
        Location pulang_lupa_dos = locationService.save(new Location("PULANG LUPA DOS", LocationType.BARANGAY));
        Location pulang_lupa_uno = locationService.save(new Location("PULANG LUPA UNO", LocationType.BARANGAY));
        Location talon_cinco = locationService.save(new Location("TALON CINCO", LocationType.BARANGAY));
        Location talon_cuatro = locationService.save(new Location("TALON CUATRO", LocationType.BARANGAY));
        Location talon_dos = locationService.save(new Location("TALON DOS", LocationType.BARANGAY));
        Location talon_tres = locationService.save(new Location("TALON TRES", LocationType.BARANGAY));
        Location talon_uno = locationService.save(new Location("TALON UNO", LocationType.BARANGAY));
        Location zapote = locationService.save(new Location("ZAPOTE", LocationType.BARANGAY));
        Location bangkal = locationService.save(new Location("BANGKAL", LocationType.BARANGAY));
        Location bel_air = locationService.save(new Location("BEL-AIR", LocationType.BARANGAY));
        Location carmona = locationService.save(new Location("CARMONA", LocationType.BARANGAY));
        Location cembo = locationService.save(new Location("CEMBO", LocationType.BARANGAY));
        Location comembo = locationService.save(new Location("COMEMBO", LocationType.BARANGAY));
        Location dasmariñas = locationService.save(new Location("DASMARIÑAS", LocationType.BARANGAY));
        Location east_rembo = locationService.save(new Location("EAST REMBO", LocationType.BARANGAY));
        Location forbes_park = locationService.save(new Location("FORBES PARK", LocationType.BARANGAY));
        Location guadalupe_nuevo = locationService.save(new Location("GUADALUPE NUEVO", LocationType.BARANGAY));
        Location guadalupe_viejo = locationService.save(new Location("GUADALUPE VIEJO", LocationType.BARANGAY));
        Location kasilawan = locationService.save(new Location("KASILAWAN", LocationType.BARANGAY));
        Location la_paz = locationService.save(new Location("LA PAZ", LocationType.BARANGAY));
        Location magallanes = locationService.save(new Location("MAGALLANES", LocationType.BARANGAY));
        Location olympia = locationService.save(new Location("OLYMPIA", LocationType.BARANGAY));
        Location palanan = locationService.save(new Location("PALANAN", LocationType.BARANGAY));
        Location pembo = locationService.save(new Location("PEMBO", LocationType.BARANGAY));
        Location pinagkaisahan = locationService.save(new Location("PINAGKAISAHAN", LocationType.BARANGAY));
        Location pio_del_pilar = locationService.save(new Location("PIO DEL PILAR", LocationType.BARANGAY));
        Location pitogo = locationService.save(new Location("PITOGO", LocationType.BARANGAY));
        Location post_proper_northside = locationService.save(new Location("POST PROPER NORTHSIDE",
                LocationType.BARANGAY));
        Location post_proper_southside = locationService.save(new Location("POST PROPER SOUTHSIDE",
                LocationType.BARANGAY));
        Location rembo = locationService.save(new Location("REMBO", LocationType.BARANGAY));
        Location rizal = locationService.save(new Location("RIZAL", LocationType.BARANGAY));
        Location san_antonio = locationService.save(new Location("SAN ANTONIO", LocationType.BARANGAY));
        Location san_lorenzo = locationService.save(new Location("SAN LORENZO", LocationType.BARANGAY));
        Location singkamas = locationService.save(new Location("SINGKAMAS", LocationType.BARANGAY));
        Location south_cembo = locationService.save(new Location("SOUTH CEMBO", LocationType.BARANGAY));
        Location tejeros = locationService.save(new Location("TEJEROS", LocationType.BARANGAY));
        Location urdaneta = locationService.save(new Location("URDANETA", LocationType.BARANGAY));
        Location valenzuela = locationService.save(new Location("VALENZUELA", LocationType.BARANGAY));
        Location west_rembo = locationService.save(new Location("WEST REMBO", LocationType.BARANGAY));
        Location acacia = locationService.save(new Location("ACACIA", LocationType.BARANGAY));
        Location baritan = locationService.save(new Location("BARITAN", LocationType.BARANGAY));
        Location bayan_bayanan = locationService.save(new Location("BAYAN-BAYANAN", LocationType.BARANGAY));
        Location concepcion = locationService.save(new Location("CONCEPCION", LocationType.BARANGAY));
        Location dampalit = locationService.save(new Location("DAMPALIT", LocationType.BARANGAY));
        Location flores = locationService.save(new Location("FLORES", LocationType.BARANGAY));
        Location hulong_duhat = locationService.save(new Location("HULONG DUHAT", LocationType.BARANGAY));
        Location ibaba = locationService.save(new Location("IBABA", LocationType.BARANGAY));
        Location longos = locationService.save(new Location("LONGOS", LocationType.BARANGAY));
        Location maysilo = locationService.save(new Location("MAYSILO", LocationType.BARANGAY));
        Location niugan = locationService.save(new Location("NIUGAN", LocationType.BARANGAY));
        Location panghulo = locationService.save(new Location("PANGHULO", LocationType.BARANGAY));
        Location potrero = locationService.save(new Location("POTRERO", LocationType.BARANGAY));
        Location san_agustin = locationService.save(new Location("SAN AGUSTIN", LocationType.BARANGAY));
        Location santolan = locationService.save(new Location("SANTOLAN", LocationType.BARANGAY));
        Location tañong = locationService.save(new Location("TAÑONG", LocationType.BARANGAY));
        Location tinajeros = locationService.save(new Location("TINAJEROS", LocationType.BARANGAY));
        Location tonsuya = locationService.save(new Location("TONSUYA", LocationType.BARANGAY));
        Location tugatog = locationService.save(new Location("TUGATOG", LocationType.BARANGAY));
        Location addition_hills = locationService.save(new Location("ADDITION HILLS", LocationType.BARANGAY));
        Location bagong_silang = locationService.save(new Location("BAGONG SILANG", LocationType.BARANGAY));
        Location barangka_drive = locationService.save(new Location("BARANGKA DRIVE", LocationType.BARANGAY));
        Location barangka_ibaba = locationService.save(new Location("BARANGKA IBABA", LocationType.BARANGAY));
        Location barangka_ilaya = locationService.save(new Location("BARANGKA ILAYA", LocationType.BARANGAY));
        Location barangka_itaas = locationService.save(new Location("BARANGKA ITAAS", LocationType.BARANGAY));
        Location buayang_bato = locationService.save(new Location("BUAYANG BATO", LocationType.BARANGAY));
        Location burol = locationService.save(new Location("BUROL", LocationType.BARANGAY));
        Location daang_bakal = locationService.save(new Location("DAANG BAKAL", LocationType.BARANGAY));
        Location hagdan_bato_itaas = locationService.save(new Location("HAGDAN BATO ITAAS", LocationType.BARANGAY));
        Location hagdan_bato_libis = locationService.save(new Location("HAGDAN BATO LIBIS", LocationType.BARANGAY));
        Location harapin_ang_bukas = locationService.save(new Location("HARAPIN ANG BUKAS", LocationType.BARANGAY));
        Location highway_hills = locationService.save(new Location("HIGHWAY HILLS", LocationType.BARANGAY));
        Location hulo = locationService.save(new Location("HULO", LocationType.BARANGAY));
        Location mabini_j_rizal = locationService.save(new Location("MABINI-J. RIZAL", LocationType.BARANGAY));
        Location malamig = locationService.save(new Location("MALAMIG", LocationType.BARANGAY));
        Location namayan = locationService.save(new Location("NAMAYAN", LocationType.BARANGAY));
        Location new_zañiga = locationService.save(new Location("NEW ZAÑIGA", LocationType.BARANGAY));
        Location old_zañiga = locationService.save(new Location("OLD ZAÑIGA", LocationType.BARANGAY));
        Location pag_asa = locationService.save(new Location("PAG-ASA", LocationType.BARANGAY));
        Location plainview = locationService.save(new Location("PLAINVIEW", LocationType.BARANGAY));
        Location pleasant_hills = locationService.save(new Location("PLEASANT HILLS", LocationType.BARANGAY));
        Location san_jose = locationService.save(new Location("SAN JOSE", LocationType.BARANGAY));
        Location vergara = locationService.save(new Location("VERGARA", LocationType.BARANGAY));
        Location wack_wack_greenhills = locationService
                .save(new Location("WACK-WACK GREENHILLS", LocationType.BARANGAY));
        Location binondo = locationService.save(new Location("BINONDO", LocationType.BARANGAY));
        Location ermita = locationService.save(new Location("ERMITA", LocationType.BARANGAY));
        Location intramuros = locationService.save(new Location("INTRAMUROS", LocationType.BARANGAY));
        Location malate = locationService.save(new Location("MALATE", LocationType.BARANGAY));
        Location paco = locationService.save(new Location("PACO", LocationType.BARANGAY));
        Location pandacan = locationService.save(new Location("PANDACAN", LocationType.BARANGAY));
        Location port_area = locationService.save(new Location("PORT AREA", LocationType.BARANGAY));
        Location quiapo = locationService.save(new Location("QUIAPO", LocationType.BARANGAY));
        Location sampaloc = locationService.save(new Location("SAMPALOC", LocationType.BARANGAY));
        Location san_andres = locationService.save(new Location("SAN ANDRES", LocationType.BARANGAY));
        Location san_miguel = locationService.save(new Location("SAN MIGUEL", LocationType.BARANGAY));
        Location san_nicolas = locationService.save(new Location("SAN NICOLAS", LocationType.BARANGAY));
        Location santa_ana = locationService.save(new Location("SANTA ANA", LocationType.BARANGAY));
        Location santa_mesa = locationService.save(new Location("SANTA MESA", LocationType.BARANGAY));
        Location tondo = locationService.save(new Location("TONDO", LocationType.BARANGAY));
        Location barangka = locationService.save(new Location("BARANGKA", LocationType.BARANGAY));
        Location calumpang = locationService.save(new Location("CALUMPANG", LocationType.BARANGAY));
        Location concepcion_i_ii = locationService.save(new Location("CONCEPCION (I/II)", LocationType.BARANGAY));
        Location fortune = locationService.save(new Location("FORTUNE", LocationType.BARANGAY));
        Location industrial_valley = locationService.save(new Location("INDUSTRIAL VALLEY", LocationType.BARANGAY));
        Location malanday = locationService.save(new Location("MALANDAY", LocationType.BARANGAY));
        Location marikina_heights = locationService.save(new Location("MARIKINA HEIGHTS", LocationType.BARANGAY));
        Location nangka = locationService.save(new Location("NANGKA", LocationType.BARANGAY));
        Location parang = locationService.save(new Location("PARANG", LocationType.BARANGAY));
        Location santa_elena = locationService.save(new Location("SANTA ELENA", LocationType.BARANGAY));
        Location alabang = locationService.save(new Location("ALABANG", LocationType.BARANGAY));
        Location ayala_alabang = locationService.save(new Location("AYALA ALABANG", LocationType.BARANGAY));
        Location bayanan = locationService.save(new Location("BAYANAN", LocationType.BARANGAY));
        Location buli = locationService.save(new Location("BULI", LocationType.BARANGAY));
        Location cupang = locationService.save(new Location("CUPANG", LocationType.BARANGAY));
        Location putatan = locationService.save(new Location("PUTATAN", LocationType.BARANGAY));
        Location sucat = locationService.save(new Location("SUCAT", LocationType.BARANGAY));
        Location tunasan = locationService.save(new Location("TUNASAN", LocationType.BARANGAY));
        Location bagumbayan_north = locationService.save(new Location("BAGUMBAYAN NORTH", LocationType.BARANGAY));
        Location bagumbayan_south = locationService.save(new Location("BAGUMBAYAN SOUTH", LocationType.BARANGAY));
        Location bangkulasi = locationService.save(new Location("BANGKULASI", LocationType.BARANGAY));
        Location daanghari = locationService.save(new Location("DAANGHARI", LocationType.BARANGAY));
        Location navotas_east = locationService.save(new Location("NAVOTAS EAST", LocationType.BARANGAY));
        Location navotas_west = locationService.save(new Location("NAVOTAS WEST", LocationType.BARANGAY));
        Location northbay_boulevard_north = locationService.save(new Location("NORTHBAY BOULEVARD NORTH",
                LocationType.BARANGAY));
        Location northbay_boulevard_south = locationService.save(new Location("NORTHBAY BOULEVARD SOUTH",
                LocationType.BARANGAY));
        Location northbay_boulevard_south_1 = locationService.save(new Location("NORTHBAY BOULEVARD SOUTH 1",
                LocationType.BARANGAY));
        Location northbay_boulevard_south_2 = locationService.save(new Location("NORTHBAY BOULEVARD SOUTH 2",
                LocationType.BARANGAY));
        Location northbay_boulevard_south_3 = locationService.save(new Location("NORTHBAY BOULEVARD SOUTH 3",
                LocationType.BARANGAY));
        Location san_rafael_village = locationService.save(new Location("SAN RAFAEL VILLAGE", LocationType.BARANGAY));
        Location sipac_almacen = locationService.save(new Location("SIPAC-ALMACEN", LocationType.BARANGAY));
        Location tangos_north = locationService.save(new Location("TANGOS NORTH", LocationType.BARANGAY));
        Location tangos_south = locationService.save(new Location("TANGOS SOUTH", LocationType.BARANGAY));
        Location tanza = locationService.save(new Location("TANZA", LocationType.BARANGAY));
        Location baclaran = locationService.save(new Location("BACLARAN", LocationType.BARANGAY));
        Location bf_homes = locationService.save(new Location("BF HOMES", LocationType.BARANGAY));
        Location don_bosco = locationService.save(new Location("DON BOSCO", LocationType.BARANGAY));
        Location don_galo = locationService.save(new Location("DON GALO", LocationType.BARANGAY));
        Location la_huerta = locationService.save(new Location("LA HUERTA", LocationType.BARANGAY));
        Location marcelo_green = locationService.save(new Location("MARCELO GREEN", LocationType.BARANGAY));
        Location merville = locationService.save(new Location("MERVILLE", LocationType.BARANGAY));
        Location moonwalk = locationService.save(new Location("MOONWALK", LocationType.BARANGAY));
        Location san_dionisio = locationService.save(new Location("SAN DIONISIO", LocationType.BARANGAY));
        Location san_martin_de_porres = locationService
                .save(new Location("SAN MARTIN DE PORRES", LocationType.BARANGAY));
        Location sun_valley = locationService.save(new Location("SUN VALLEY", LocationType.BARANGAY));
        Location tambo = locationService.save(new Location("TAMBO", LocationType.BARANGAY));
        Location vitalez = locationService.save(new Location("VITALEZ", LocationType.BARANGAY));
        Location malibay = locationService.save(new Location("MALIBAY", LocationType.BARANGAY));
        Location manila_bay_reclamation = locationService.save(new Location("MANILA BAY RECLAMATION",
                LocationType.BARANGAY));
        Location maricaban = locationService.save(new Location("MARICABAN", LocationType.BARANGAY));
        Location picc = locationService.save(new Location("PICC", LocationType.BARANGAY));
        Location villamor_airbase = locationService.save(new Location("VILLAMOR AIRBASE", LocationType.BARANGAY));
        Location bagong_ilog = locationService.save(new Location("BAGONG ILOG", LocationType.BARANGAY));
        Location bagong_katipunan = locationService.save(new Location("BAGONG KATIPUNAN", LocationType.BARANGAY));
        Location bambang = locationService.save(new Location("BAMBANG", LocationType.BARANGAY));
        Location buting = locationService.save(new Location("BUTING", LocationType.BARANGAY));
        Location caniogan = locationService.save(new Location("CANIOGAN", LocationType.BARANGAY));
        Location dela_paz = locationService.save(new Location("DELA PAZ", LocationType.BARANGAY));
        Location kalawaan = locationService.save(new Location("KALAWAAN", LocationType.BARANGAY));
        Location kapasigan = locationService.save(new Location("KAPASIGAN", LocationType.BARANGAY));
        Location kapitolyo = locationService.save(new Location("KAPITOLYO", LocationType.BARANGAY));
        Location malinao = locationService.save(new Location("MALINAO", LocationType.BARANGAY));
        Location mauway = locationService.save(new Location("MAUWAY", LocationType.BARANGAY));
        Location maybunga = locationService.save(new Location("MAYBUNGA", LocationType.BARANGAY));
        Location oranbo = locationService.save(new Location("ORANBO", LocationType.BARANGAY));
        Location palatiw = locationService.save(new Location("PALATIW", LocationType.BARANGAY));
        Location pinagbuhatan = locationService.save(new Location("PINAGBUHATAN", LocationType.BARANGAY));
        Location pineda = locationService.save(new Location("PINEDA", LocationType.BARANGAY));
        Location rosario = locationService.save(new Location("ROSARIO", LocationType.BARANGAY));
        Location sagad = locationService.save(new Location("SAGAD", LocationType.BARANGAY));
        Location san_joaquin = locationService.save(new Location("SAN JOAQUIN", LocationType.BARANGAY));
        Location santa_lucia = locationService.save(new Location("SANTA LUCIA", LocationType.BARANGAY));
        Location santa_rosa = locationService.save(new Location("SANTA ROSA", LocationType.BARANGAY));
        Location sumilang = locationService.save(new Location("SUMILANG", LocationType.BARANGAY));
        Location ugong = locationService.save(new Location("UGONG", LocationType.BARANGAY));
        Location aguho = locationService.save(new Location("AGUHO", LocationType.BARANGAY));
        Location magtanggol = locationService.save(new Location("MAGTANGGOL", LocationType.BARANGAY));
        Location martires = locationService.save(new Location("MARTIRES", LocationType.BARANGAY));
        Location santo_rosario_kanluran = locationService.save(new Location("SANTO ROSARIO KANLURAN",
                LocationType.BARANGAY));
        Location santo_rosario_silangan = locationService.save(new Location("SANTO ROSARIO SILANGAN",
                LocationType.BARANGAY));
        Location tabacalera = locationService.save(new Location("TABACALERA", LocationType.BARANGAY));
        Location alicia = locationService.save(new Location("ALICIA", LocationType.BARANGAY));
        Location amihan = locationService.save(new Location("AMIHAN", LocationType.BARANGAY));
        Location apolonio_samson = locationService.save(new Location("APOLONIO SAMSON", LocationType.BARANGAY));
        Location bagbag = locationService.save(new Location("BAGBAG", LocationType.BARANGAY));
        Location bagong_lipunan_ng_crame = locationService.save(new Location("BAGONG LIPUNAN NG CRAME",
                LocationType.BARANGAY));
        Location bagong_pag_asa = locationService.save(new Location("BAGONG PAG-ASA", LocationType.BARANGAY));
        Location bagong_silangan = locationService.save(new Location("BAGONG SILANGAN", LocationType.BARANGAY));
        Location bagumbayan = locationService.save(new Location("BAGUMBAYAN", LocationType.BARANGAY));
        Location bagumbuhay = locationService.save(new Location("BAGUMBUHAY", LocationType.BARANGAY));
        Location bahay_toro = locationService.save(new Location("BAHAY TORO", LocationType.BARANGAY));
        Location balingasa = locationService.save(new Location("BALINGASA", LocationType.BARANGAY));
        Location balonbato = locationService.save(new Location("BALONBATO", LocationType.BARANGAY));
        Location batasan_hills = locationService.save(new Location("BATASAN HILLS", LocationType.BARANGAY));
        Location bayanihan = locationService.save(new Location("BAYANIHAN", LocationType.BARANGAY));
        Location blue_ridge_a_b = locationService.save(new Location("BLUE RIDGE (A/B)", LocationType.BARANGAY));
        Location botocan = locationService.save(new Location("BOTOCAN", LocationType.BARANGAY));
        Location bungad = locationService.save(new Location("BUNGAD", LocationType.BARANGAY));
        Location camp_aguinaldo = locationService.save(new Location("CAMP AGUINALDO", LocationType.BARANGAY));
        Location capri = locationService.save(new Location("CAPRI", LocationType.BARANGAY));
        Location central = locationService.save(new Location("CENTRAL", LocationType.BARANGAY));
        Location commonwealth = locationService.save(new Location("COMMONWEALTH", LocationType.BARANGAY));
        Location culiat = locationService.save(new Location("CULIAT", LocationType.BARANGAY));
        Location damar = locationService.save(new Location("DAMAR", LocationType.BARANGAY));
        Location damayang_lagi = locationService.save(new Location("DAMAYANG LAGI", LocationType.BARANGAY));
        Location del_monte = locationService.save(new Location("DEL MONTE", LocationType.BARANGAY));
        Location dioquino_zobel = locationService.save(new Location("DIOQUINO ZOBEL", LocationType.BARANGAY));
        Location don_manuel = locationService.save(new Location("DON MANUEL", LocationType.BARANGAY));
        Location doña_aurora = locationService.save(new Location("DOÑA AURORA", LocationType.BARANGAY));
        Location doña_imelda = locationService.save(new Location("DOÑA IMELDA", LocationType.BARANGAY));
        Location doña_josefa = locationService.save(new Location("DOÑA JOSEFA", LocationType.BARANGAY));
        Location duyan_duyan = locationService.save(new Location("DUYAN DUYAN", LocationType.BARANGAY));
        Location e_rodriguez = locationService.save(new Location("E. RODRIGUEZ", LocationType.BARANGAY));
        Location east_kamias = locationService.save(new Location("EAST KAMIAS", LocationType.BARANGAY));
        Location escopa_i_iv = locationService.save(new Location("ESCOPA (I-IV)", LocationType.BARANGAY));
        Location fairview = locationService.save(new Location("FAIRVIEW", LocationType.BARANGAY));
        Location greater_lagro = locationService.save(new Location("GREATER LAGRO", LocationType.BARANGAY));
        Location gulod = locationService.save(new Location("GULOD", LocationType.BARANGAY));
        Location holy_spirit = locationService.save(new Location("HOLY SPIRIT", LocationType.BARANGAY));
        Location horseshoe = locationService.save(new Location("HORSESHOE", LocationType.BARANGAY));
        Location immaculate_concepcion = locationService.save(new Location("IMMACULATE CONCEPCION",
                LocationType.BARANGAY));
        Location kaligayahan = locationService.save(new Location("KALIGAYAHAN", LocationType.BARANGAY));
        Location kalusugan = locationService.save(new Location("KALUSUGAN", LocationType.BARANGAY));
        Location kamuning = locationService.save(new Location("KAMUNING", LocationType.BARANGAY));
        Location katipunan = locationService.save(new Location("KATIPUNAN", LocationType.BARANGAY));
        Location kaunlaran = locationService.save(new Location("KAUNLARAN", LocationType.BARANGAY));
        Location kristong_hari = locationService.save(new Location("KRISTONG HARI", LocationType.BARANGAY));
        Location krus_na_ligas = locationService.save(new Location("KRUS NA LIGAS", LocationType.BARANGAY));
        Location laging_handa = locationService.save(new Location("LAGING HANDA", LocationType.BARANGAY));
        Location libis = locationService.save(new Location("LIBIS", LocationType.BARANGAY));
        Location lourdes = locationService.save(new Location("LOURDES", LocationType.BARANGAY));
        Location loyola_heights = locationService.save(new Location("LOYOLA HEIGHTS", LocationType.BARANGAY));
        Location malaya = locationService.save(new Location("MALAYA", LocationType.BARANGAY));
        Location mangga = locationService.save(new Location("MANGGA", LocationType.BARANGAY));
        Location manresa = locationService.save(new Location("MANRESA", LocationType.BARANGAY));
        Location mariana = locationService.save(new Location("MARIANA", LocationType.BARANGAY));
        Location mariblo = locationService.save(new Location("MARIBLO", LocationType.BARANGAY));
        Location marilag = locationService.save(new Location("MARILAG", LocationType.BARANGAY));
        Location masagana = locationService.save(new Location("MASAGANA", LocationType.BARANGAY));
        Location masambong = locationService.save(new Location("MASAMBONG", LocationType.BARANGAY));
        Location matandang_balara = locationService.save(new Location("MATANDANG BALARA", LocationType.BARANGAY));
        Location milagrosa = locationService.save(new Location("MILAGROSA", LocationType.BARANGAY));
        Location ns_amoranto = locationService.save(new Location("N.S. AMORANTO", LocationType.BARANGAY));
        Location nagkaisang_nayon = locationService.save(new Location("NAGKAISANG NAYON", LocationType.BARANGAY));
        Location nayong_kanluran = locationService.save(new Location("NAYONG KANLURAN", LocationType.BARANGAY));
        Location new_era = locationService.save(new Location("NEW ERA", LocationType.BARANGAY));
        Location north_fairview = locationService.save(new Location("NORTH FAIRVIEW", LocationType.BARANGAY));
        Location novaliches = locationService.save(new Location("NOVALICHES", LocationType.BARANGAY));
        Location obrero = locationService.save(new Location("OBRERO", LocationType.BARANGAY));
        Location old_capitol_site = locationService.save(new Location("OLD CAPITOL SITE", LocationType.BARANGAY));
        Location paang_bundok = locationService.save(new Location("PAANG BUNDOK", LocationType.BARANGAY));
        Location pag_ibig_sa_nayon = locationService.save(new Location("PAG-IBIG SA NAYON", LocationType.BARANGAY));
        Location paligsahan = locationService.save(new Location("PALIGSAHAN", LocationType.BARANGAY));
        Location paltok = locationService.save(new Location("PALTOK", LocationType.BARANGAY));
        Location pansol = locationService.save(new Location("PANSOL", LocationType.BARANGAY));
        Location paraiso = locationService.save(new Location("PARAISO", LocationType.BARANGAY));
        Location pasong_putik = locationService.save(new Location("PASONG PUTIK", LocationType.BARANGAY));
        Location pasong_tamo = locationService.save(new Location("PASONG TAMO", LocationType.BARANGAY));
        Location payatas = locationService.save(new Location("PAYATAS", LocationType.BARANGAY));
        Location phil_am = locationService.save(new Location("PHIL-AM", LocationType.BARANGAY));
        Location pinyahan = locationService.save(new Location("PINYAHAN", LocationType.BARANGAY));
        Location project_6 = locationService.save(new Location("PROJECT 6", LocationType.BARANGAY));
        Location quirino_2_a_c = locationService.save(new Location("QUIRINO 2 (A-C)", LocationType.BARANGAY));
        Location quirino_3_a_b = locationService.save(new Location("QUIRINO 3 (A-B)", LocationType.BARANGAY));
        Location roxas = locationService.save(new Location("ROXAS", LocationType.BARANGAY));
        Location sacred_heart = locationService.save(new Location("SACRED HEART", LocationType.BARANGAY));
        Location salvacion = locationService.save(new Location("SALVACION", LocationType.BARANGAY));
        Location san_bartolome = locationService.save(new Location("SAN BARTOLOME", LocationType.BARANGAY));
        Location san_isidro_galas = locationService.save(new Location("SAN ISIDRO GALAS", LocationType.BARANGAY));
        Location san_isidro_labrador = locationService.save(new Location("SAN ISIDRO LABRADOR", LocationType.BARANGAY));
        Location santa_monica = locationService.save(new Location("SANTA MONICA", LocationType.BARANGAY));
        Location santa_teresita = locationService.save(new Location("SANTA TERESITA", LocationType.BARANGAY));
        Location santo_domingo = locationService.save(new Location("SANTO DOMINGO", LocationType.BARANGAY));
        Location santol = locationService.save(new Location("SANTOL", LocationType.BARANGAY));
        Location sauyo = locationService.save(new Location("SAUYO", LocationType.BARANGAY));
        Location siena = locationService.save(new Location("SIENA", LocationType.BARANGAY));
        Location sikatuna_village = locationService.save(new Location("SIKATUNA VILLAGE", LocationType.BARANGAY));
        Location socorro_cubao = locationService.save(new Location("SOCORRO (CUBAO)", LocationType.BARANGAY));
        Location st_ignatius = locationService.save(new Location("ST. IGNATIUS", LocationType.BARANGAY));
        Location st_peter = locationService.save(new Location("ST. PETER", LocationType.BARANGAY));
        Location tagumpay = locationService.save(new Location("TAGUMPAY", LocationType.BARANGAY));
        Location talayan = locationService.save(new Location("TALAYAN", LocationType.BARANGAY));
        Location tandang_sora = locationService.save(new Location("TANDANG SORA", LocationType.BARANGAY));
        Location tatalon = locationService.save(new Location("TATALON", LocationType.BARANGAY));
        Location teachers_village = locationService.save(new Location("TEACHER'S VILLAGE", LocationType.BARANGAY));
        Location ugong_norte = locationService.save(new Location("UGONG NORTE", LocationType.BARANGAY));
        Location unang_sigaw = locationService.save(new Location("UNANG SIGAW", LocationType.BARANGAY));
        Location up_campus = locationService.save(new Location("UP CAMPUS", LocationType.BARANGAY));
        Location up_village = locationService.save(new Location("UP VILLAGE", LocationType.BARANGAY));
        Location valencia = locationService.save(new Location("VALENCIA", LocationType.BARANGAY));
        Location vasra = locationService.save(new Location("VASRA", LocationType.BARANGAY));
        Location veterans_village = locationService.save(new Location("VETERANS VILLAGE", LocationType.BARANGAY));
        Location villa_maria_clara = locationService.save(new Location("VILLA MARIA CLARA", LocationType.BARANGAY));
        Location west_kamias = locationService.save(new Location("WEST KAMIAS", LocationType.BARANGAY));
        Location west_triangle = locationService.save(new Location("WEST TRIANGLE", LocationType.BARANGAY));
        Location white_plains = locationService.save(new Location("WHITE PLAINS", LocationType.BARANGAY));
        Location balong_bato = locationService.save(new Location("BALONG-BATO", LocationType.BARANGAY));
        Location batis = locationService.save(new Location("BATIS", LocationType.BARANGAY));
        Location corazon_de_jesus = locationService.save(new Location("CORAZON DE JESUS", LocationType.BARANGAY));
        Location ermitaño = locationService.save(new Location("ERMITAÑO", LocationType.BARANGAY));
        Location greenhills = locationService.save(new Location("GREENHILLS", LocationType.BARANGAY));
        Location isabelita = locationService.save(new Location("ISABELITA", LocationType.BARANGAY));
        Location kabayanan = locationService.save(new Location("KABAYANAN", LocationType.BARANGAY));
        Location little_baguio = locationService.save(new Location("LITTLE BAGUIO", LocationType.BARANGAY));
        Location maytunas = locationService.save(new Location("MAYTUNAS", LocationType.BARANGAY));
        Location onse = locationService.save(new Location("ONSE", LocationType.BARANGAY));
        Location pasadena = locationService.save(new Location("PASADENA", LocationType.BARANGAY));
        Location pedro_cruz = locationService.save(new Location("PEDRO CRUZ", LocationType.BARANGAY));
        Location progreso = locationService.save(new Location("PROGRESO", LocationType.BARANGAY));
        Location rivera = locationService.save(new Location("RIVERA", LocationType.BARANGAY));
        Location salapan = locationService.save(new Location("SALAPAN", LocationType.BARANGAY));
        Location san_perfecto = locationService.save(new Location("SAN PERFECTO", LocationType.BARANGAY));
        Location st_joseph = locationService.save(new Location("ST. JOSEPH", LocationType.BARANGAY));
        Location tibagan = locationService.save(new Location("TIBAGAN", LocationType.BARANGAY));
        Location west_crame = locationService.save(new Location("WEST CRAME", LocationType.BARANGAY));
        Location calzada = locationService.save(new Location("CALZADA", LocationType.BARANGAY));
        Location central_bicutan = locationService.save(new Location("CENTRAL BICUTAN", LocationType.BARANGAY));
        Location central_signal_village = locationService.save(new Location("CENTRAL SIGNAL VILLAGE",
                LocationType.BARANGAY));
        Location fort_bonifacio = locationService.save(new Location("FORT BONIFACIO", LocationType.BARANGAY));
        Location hagonoy = locationService.save(new Location("HAGONOY", LocationType.BARANGAY));
        Location ibayo_tipas = locationService.save(new Location("IBAYO TIPAS", LocationType.BARANGAY));
        Location katuparan = locationService.save(new Location("KATUPARAN", LocationType.BARANGAY));
        Location ligid_tipas = locationService.save(new Location("LIGID TIPAS", LocationType.BARANGAY));
        Location lower_bicutan = locationService.save(new Location("LOWER BICUTAN", LocationType.BARANGAY));
        Location maharlika_village = locationService.save(new Location("MAHARLIKA VILLAGE", LocationType.BARANGAY));
        Location napindan = locationService.save(new Location("NAPINDAN", LocationType.BARANGAY));
        Location new_lower_bicutan = locationService.save(new Location("NEW LOWER BICUTAN", LocationType.BARANGAY));
        Location north_daang_hari = locationService.save(new Location("NORTH DAANG HARI", LocationType.BARANGAY));
        Location north_signal_village = locationService
                .save(new Location("NORTH SIGNAL VILLAGE", LocationType.BARANGAY));
        Location palingon = locationService.save(new Location("PALINGON", LocationType.BARANGAY));
        Location pinagsama = locationService.save(new Location("PINAGSAMA", LocationType.BARANGAY));
        Location south_daang_hari = locationService.save(new Location("SOUTH DAANG HARI", LocationType.BARANGAY));
        Location south_signal_village = locationService
                .save(new Location("SOUTH SIGNAL VILLAGE", LocationType.BARANGAY));
        Location tanyag = locationService.save(new Location("TANYAG", LocationType.BARANGAY));
        Location tuktukan = locationService.save(new Location("TUKTUKAN", LocationType.BARANGAY));
        Location upper_bicutan = locationService.save(new Location("UPPER BICUTAN", LocationType.BARANGAY));
        Location ususan = locationService.save(new Location("USUSAN", LocationType.BARANGAY));
        Location wawa = locationService.save(new Location("WAWA", LocationType.BARANGAY));
        Location western_bicutan = locationService.save(new Location("WESTERN BICUTAN", LocationType.BARANGAY));
        Location arkong_bato = locationService.save(new Location("ARKONG BATO", LocationType.BARANGAY));
        Location balangkas = locationService.save(new Location("BALANGKAS", LocationType.BARANGAY));
        Location bignay = locationService.save(new Location("BIGNAY", LocationType.BARANGAY));
        Location bisig = locationService.save(new Location("BISIG", LocationType.BARANGAY));
        Location canumay = locationService.save(new Location("CANUMAY", LocationType.BARANGAY));
        Location coloong = locationService.save(new Location("COLOONG", LocationType.BARANGAY));
        Location dalandanan = locationService.save(new Location("DALANDANAN", LocationType.BARANGAY));
        Location general_t_de_leon = locationService.save(new Location("GENERAL T. DE LEON", LocationType.BARANGAY));
        Location isla = locationService.save(new Location("ISLA", LocationType.BARANGAY));
        Location karuhatan = locationService.save(new Location("KARUHATAN", LocationType.BARANGAY));
        Location lawang_bato = locationService.save(new Location("LAWANG BATO", LocationType.BARANGAY));
        Location lingunan = locationService.save(new Location("LINGUNAN", LocationType.BARANGAY));
        Location mabolo = locationService.save(new Location("MABOLO", LocationType.BARANGAY));
        Location malinta = locationService.save(new Location("MALINTA", LocationType.BARANGAY));
        Location mapulang_lupa = locationService.save(new Location("MAPULANG LUPA", LocationType.BARANGAY));
        Location marulas = locationService.save(new Location("MARULAS", LocationType.BARANGAY));
        Location maysan = locationService.save(new Location("MAYSAN", LocationType.BARANGAY));
        Location palasan = locationService.save(new Location("PALASAN", LocationType.BARANGAY));
        Location pariancillo_villa = locationService.save(new Location("PARIANCILLO VILLA", LocationType.BARANGAY));
        Location paso_de_blas = locationService.save(new Location("PASO DE BLAS", LocationType.BARANGAY));
        Location pasolo = locationService.save(new Location("PASOLO", LocationType.BARANGAY));
        Location polo = locationService.save(new Location("POLO", LocationType.BARANGAY));
        Location punturin = locationService.save(new Location("PUNTURIN", LocationType.BARANGAY));
        Location rincon = locationService.save(new Location("RINCON", LocationType.BARANGAY));
        Location tagalag = locationService.save(new Location("TAGALAG", LocationType.BARANGAY));
        Location veinte_reales = locationService.save(new Location("VEINTE REALES", LocationType.BARANGAY));
        Location camarin = locationService.save(new Location("CAMARIN", LocationType.BARANGAY));

        Location caloocan = locationService.save(new Location("CALOOCAN", LocationType.CITY));
        Location las_piñas = locationService.save(new Location("LAS PIÑAS", LocationType.CITY));
        Location makati = locationService.save(new Location("MAKATI", LocationType.CITY));
        Location malabon = locationService.save(new Location("MALABON", LocationType.CITY));
        Location mandaluyong = locationService.save(new Location("MANDALUYONG", LocationType.CITY));
        Location manila = locationService.save(new Location("MANILA", LocationType.CITY));
        Location marikina = locationService.save(new Location("MARIKINA", LocationType.CITY));
        Location muntinlupa = locationService.save(new Location("MUNTINLUPA", LocationType.CITY));
        Location navotas = locationService.save(new Location("NAVOTAS", LocationType.CITY));
        Location parañaque = locationService.save(new Location("PARAÑAQUE", LocationType.CITY));
        Location pasay = locationService.save(new Location("PASAY", LocationType.CITY));
        Location pasig = locationService.save(new Location("PASIG", LocationType.CITY));
        Location pateros = locationService.save(new Location("PATEROS", LocationType.CITY));
        Location quezon_city = locationService.save(new Location("QUEZON CITY", LocationType.CITY));
        Location san_juan = locationService.save(new Location("SAN JUAN", LocationType.CITY));
        Location taguig = locationService.save(new Location("TAGUIG", LocationType.CITY));
        Location valenzuela_city = locationService.save(new Location("VALENZUELA CITY", LocationType.CITY));

        Location metro_manila = locationService.save(new Location("METRO MANILA", LocationType.PROVINCE));
        locationTreeService.save(new LocationTree(caloocan, metro_manila));
        locationTreeService.save(new LocationTree(las_piñas, metro_manila));
        locationTreeService.save(new LocationTree(makati, metro_manila));
        locationTreeService.save(new LocationTree(malabon, metro_manila));
        locationTreeService.save(new LocationTree(mandaluyong, metro_manila));
        locationTreeService.save(new LocationTree(manila, metro_manila));
        locationTreeService.save(new LocationTree(marikina, metro_manila));
        locationTreeService.save(new LocationTree(muntinlupa, metro_manila));
        locationTreeService.save(new LocationTree(navotas, metro_manila));
        locationTreeService.save(new LocationTree(parañaque, metro_manila));
        locationTreeService.save(new LocationTree(pasay, metro_manila));
        locationTreeService.save(new LocationTree(pasig, metro_manila));
        locationTreeService.save(new LocationTree(pateros, metro_manila));
        locationTreeService.save(new LocationTree(quezon_city, metro_manila));
        locationTreeService.save(new LocationTree(san_juan, metro_manila));
        locationTreeService.save(new LocationTree(taguig, metro_manila));
        locationTreeService.save(new LocationTree(valenzuela_city, metro_manila));

        locationTreeService.save(new LocationTree(san_jose_del_monte, bulacan));
        locationTreeService.save(new LocationTree(santa_maria, bulacan));
        locationTreeService.save(new LocationTree(citrus, san_jose_del_monte));
        locationTreeService.save(new LocationTree(ciudad_real, san_jose_del_monte));
        locationTreeService.save(new LocationTree(dulong_bayan, san_jose_del_monte));
        locationTreeService.save(new LocationTree(fatima, san_jose_del_monte));
        locationTreeService.save(new LocationTree(francisco_homes, san_jose_del_monte));
        locationTreeService.save(new LocationTree(gaya_gaya, san_jose_del_monte));
        locationTreeService.save(new LocationTree(graceville, san_jose_del_monte));
        locationTreeService.save(new LocationTree(gumaoc, san_jose_del_monte));
        locationTreeService.save(new LocationTree(kaybanban, san_jose_del_monte));
        locationTreeService.save(new LocationTree(kaypian, san_jose_del_monte));
        locationTreeService.save(new LocationTree(lawang_pare, san_jose_del_monte));
        locationTreeService.save(new LocationTree(minuyan, san_jose_del_monte));
        locationTreeService.save(new LocationTree(muzon, san_jose_del_monte));
        locationTreeService.save(new LocationTree(paradise, san_jose_del_monte));
        locationTreeService.save(new LocationTree(poblacion, san_jose_del_monte));
        locationTreeService.save(new LocationTree(san_isidro, san_jose_del_monte));
        locationTreeService.save(new LocationTree(san_manuel, san_jose_del_monte));
        locationTreeService.save(new LocationTree(san_martin, san_jose_del_monte));
        locationTreeService.save(new LocationTree(san_pedro, san_jose_del_monte));
        locationTreeService.save(new LocationTree(san_rafael, san_jose_del_monte));
        locationTreeService.save(new LocationTree(san_roque, san_jose_del_monte));
        locationTreeService.save(new LocationTree(sapang_palay, san_jose_del_monte));
        locationTreeService.save(new LocationTree(saint_martin_de_porres, san_jose_del_monte));
        locationTreeService.save(new LocationTree(santa_cruz, san_jose_del_monte));
        locationTreeService.save(new LocationTree(santo_cristo, san_jose_del_monte));
        locationTreeService.save(new LocationTree(santo_niño, san_jose_del_monte));
        locationTreeService.save(new LocationTree(tungkong_mangga, san_jose_del_monte));
        locationTreeService.save(new LocationTree(maharlika, san_jose_del_monte));
        locationTreeService.save(new LocationTree(assumption, san_jose_del_monte));
        locationTreeService.save(new LocationTree(bagong_buhay, san_jose_del_monte));
        locationTreeService.save(new LocationTree(balasing, santa_maria));
        locationTreeService.save(new LocationTree(buenavista, santa_maria));
        locationTreeService.save(new LocationTree(bulac, santa_maria));
        locationTreeService.save(new LocationTree(camangyanan, santa_maria));
        locationTreeService.save(new LocationTree(catmon, santa_maria));
        locationTreeService.save(new LocationTree(caypombo, santa_maria));
        locationTreeService.save(new LocationTree(caysio, santa_maria));
        locationTreeService.save(new LocationTree(guyong, santa_maria));
        locationTreeService.save(new LocationTree(lalakhan, santa_maria));
        locationTreeService.save(new LocationTree(mag_asawang_sapa, santa_maria));
        locationTreeService.save(new LocationTree(mahabang_parang, santa_maria));
        locationTreeService.save(new LocationTree(manggahan, santa_maria));
        locationTreeService.save(new LocationTree(parada, santa_maria));
        locationTreeService.save(new LocationTree(poblacion, santa_maria));
        locationTreeService.save(new LocationTree(pulong_buhangin, santa_maria));
        locationTreeService.save(new LocationTree(san_gabriel, santa_maria));
        locationTreeService.save(new LocationTree(san_jose_patag, santa_maria));
        locationTreeService.save(new LocationTree(san_vicente, santa_maria));
        locationTreeService.save(new LocationTree(santa_clara, santa_maria));
        locationTreeService.save(new LocationTree(santa_cruz, santa_maria));
        locationTreeService.save(new LocationTree(santo_tomas, santa_maria));
        locationTreeService.save(new LocationTree(silangan, santa_maria));
        locationTreeService.save(new LocationTree(tumana, santa_maria));
        locationTreeService.save(new LocationTree(bagbaguin, santa_maria));

        locationTreeService.save(new LocationTree(a_mabini, caloocan));
        locationTreeService.save(new LocationTree(baesa, caloocan));
        locationTreeService.save(new LocationTree(bagong_barrio, caloocan));
        locationTreeService.save(new LocationTree(barrio_san_jose, caloocan));
        locationTreeService.save(new LocationTree(biglang_awa, caloocan));
        locationTreeService.save(new LocationTree(dagat_dagatan, caloocan));
        locationTreeService.save(new LocationTree(grace_park_east, caloocan));
        locationTreeService.save(new LocationTree(grace_park_west, caloocan));
        locationTreeService.save(new LocationTree(heroes_del_96, caloocan));
        locationTreeService.save(new LocationTree(kaunlaran_village, caloocan));
        locationTreeService.save(new LocationTree(libis_reparo, caloocan));
        locationTreeService.save(new LocationTree(maypajo, caloocan));
        locationTreeService.save(new LocationTree(monumento, caloocan));
        locationTreeService.save(new LocationTree(morning_breeze, caloocan));
        locationTreeService.save(new LocationTree(sangandaan, caloocan));
        locationTreeService.save(new LocationTree(santa_quiteria, caloocan));
        locationTreeService.save(new LocationTree(talipapa, caloocan));
        locationTreeService.save(new LocationTree(university_hills, caloocan));
        locationTreeService.save(new LocationTree(almanza_dos, las_piñas));
        locationTreeService.save(new LocationTree(almanza_uno, las_piñas));
        locationTreeService.save(new LocationTree(caa_bf_international, las_piñas));
        locationTreeService.save(new LocationTree(daniel_fajardo, las_piñas));
        locationTreeService.save(new LocationTree(elias_aldana, las_piñas));
        locationTreeService.save(new LocationTree(ilaya, las_piñas));
        locationTreeService.save(new LocationTree(manuyo_dos, las_piñas));
        locationTreeService.save(new LocationTree(manuyo_uno, las_piñas));
        locationTreeService.save(new LocationTree(pamplona_dos, las_piñas));
        locationTreeService.save(new LocationTree(pamplona_tres, las_piñas));
        locationTreeService.save(new LocationTree(pamplona_uno, las_piñas));
        locationTreeService.save(new LocationTree(pilar_village, las_piñas));
        locationTreeService.save(new LocationTree(pulang_lupa_dos, las_piñas));
        locationTreeService.save(new LocationTree(pulang_lupa_uno, las_piñas));
        locationTreeService.save(new LocationTree(talon_cinco, las_piñas));
        locationTreeService.save(new LocationTree(talon_cuatro, las_piñas));
        locationTreeService.save(new LocationTree(talon_dos, las_piñas));
        locationTreeService.save(new LocationTree(talon_tres, las_piñas));
        locationTreeService.save(new LocationTree(talon_uno, las_piñas));
        locationTreeService.save(new LocationTree(zapote, las_piñas));
        locationTreeService.save(new LocationTree(bangkal, makati));
        locationTreeService.save(new LocationTree(bel_air, makati));
        locationTreeService.save(new LocationTree(carmona, makati));
        locationTreeService.save(new LocationTree(cembo, makati));
        locationTreeService.save(new LocationTree(comembo, makati));
        locationTreeService.save(new LocationTree(dasmariñas, makati));
        locationTreeService.save(new LocationTree(east_rembo, makati));
        locationTreeService.save(new LocationTree(forbes_park, makati));
        locationTreeService.save(new LocationTree(guadalupe_nuevo, makati));
        locationTreeService.save(new LocationTree(guadalupe_viejo, makati));
        locationTreeService.save(new LocationTree(kasilawan, makati));
        locationTreeService.save(new LocationTree(la_paz, makati));
        locationTreeService.save(new LocationTree(magallanes, makati));
        locationTreeService.save(new LocationTree(olympia, makati));
        locationTreeService.save(new LocationTree(palanan, makati));
        locationTreeService.save(new LocationTree(pembo, makati));
        locationTreeService.save(new LocationTree(pinagkaisahan, makati));
        locationTreeService.save(new LocationTree(pio_del_pilar, makati));
        locationTreeService.save(new LocationTree(pitogo, makati));
        locationTreeService.save(new LocationTree(poblacion, makati));
        locationTreeService.save(new LocationTree(post_proper_northside, makati));
        locationTreeService.save(new LocationTree(post_proper_southside, makati));
        locationTreeService.save(new LocationTree(rembo, makati));
        locationTreeService.save(new LocationTree(rizal, makati));
        locationTreeService.save(new LocationTree(san_antonio, makati));
        locationTreeService.save(new LocationTree(san_isidro, makati));
        locationTreeService.save(new LocationTree(san_lorenzo, makati));
        locationTreeService.save(new LocationTree(santa_cruz, makati));
        locationTreeService.save(new LocationTree(singkamas, makati));
        locationTreeService.save(new LocationTree(south_cembo, makati));
        locationTreeService.save(new LocationTree(tejeros, makati));
        locationTreeService.save(new LocationTree(urdaneta, makati));
        locationTreeService.save(new LocationTree(valenzuela, makati));
        locationTreeService.save(new LocationTree(west_rembo, makati));
        locationTreeService.save(new LocationTree(acacia, malabon));
        locationTreeService.save(new LocationTree(baritan, malabon));
        locationTreeService.save(new LocationTree(bayan_bayanan, malabon));
        locationTreeService.save(new LocationTree(catmon, malabon));
        locationTreeService.save(new LocationTree(concepcion, malabon));
        locationTreeService.save(new LocationTree(dampalit, malabon));
        locationTreeService.save(new LocationTree(flores, malabon));
        locationTreeService.save(new LocationTree(hulong_duhat, malabon));
        locationTreeService.save(new LocationTree(ibaba, malabon));
        locationTreeService.save(new LocationTree(longos, malabon));
        locationTreeService.save(new LocationTree(maysilo, malabon));
        locationTreeService.save(new LocationTree(muzon, malabon));
        locationTreeService.save(new LocationTree(niugan, malabon));
        locationTreeService.save(new LocationTree(panghulo, malabon));
        locationTreeService.save(new LocationTree(potrero, malabon));
        locationTreeService.save(new LocationTree(san_agustin, malabon));
        locationTreeService.save(new LocationTree(santolan, malabon));
        locationTreeService.save(new LocationTree(tañong, malabon));
        locationTreeService.save(new LocationTree(tinajeros, malabon));
        locationTreeService.save(new LocationTree(tonsuya, malabon));
        locationTreeService.save(new LocationTree(tugatog, malabon));
        locationTreeService.save(new LocationTree(addition_hills, mandaluyong));
        locationTreeService.save(new LocationTree(bagong_silang, mandaluyong));
        locationTreeService.save(new LocationTree(barangka_drive, mandaluyong));
        locationTreeService.save(new LocationTree(barangka_ibaba, mandaluyong));
        locationTreeService.save(new LocationTree(barangka_ilaya, mandaluyong));
        locationTreeService.save(new LocationTree(barangka_itaas, mandaluyong));
        locationTreeService.save(new LocationTree(buayang_bato, mandaluyong));
        locationTreeService.save(new LocationTree(burol, mandaluyong));
        locationTreeService.save(new LocationTree(daang_bakal, mandaluyong));
        locationTreeService.save(new LocationTree(hagdan_bato_itaas, mandaluyong));
        locationTreeService.save(new LocationTree(hagdan_bato_libis, mandaluyong));
        locationTreeService.save(new LocationTree(harapin_ang_bukas, mandaluyong));
        locationTreeService.save(new LocationTree(highway_hills, mandaluyong));
        locationTreeService.save(new LocationTree(hulo, mandaluyong));
        locationTreeService.save(new LocationTree(mabini_j_rizal, mandaluyong));
        locationTreeService.save(new LocationTree(malamig, mandaluyong));
        locationTreeService.save(new LocationTree(namayan, mandaluyong));
        locationTreeService.save(new LocationTree(new_zañiga, mandaluyong));
        locationTreeService.save(new LocationTree(old_zañiga, mandaluyong));
        locationTreeService.save(new LocationTree(pag_asa, mandaluyong));
        locationTreeService.save(new LocationTree(plainview, mandaluyong));
        locationTreeService.save(new LocationTree(pleasant_hills, mandaluyong));
        locationTreeService.save(new LocationTree(poblacion, mandaluyong));
        locationTreeService.save(new LocationTree(san_jose, mandaluyong));
        locationTreeService.save(new LocationTree(vergara, mandaluyong));
        locationTreeService.save(new LocationTree(wack_wack_greenhills, mandaluyong));
        locationTreeService.save(new LocationTree(binondo, manila));
        locationTreeService.save(new LocationTree(ermita, manila));
        locationTreeService.save(new LocationTree(intramuros, manila));
        locationTreeService.save(new LocationTree(malate, manila));
        locationTreeService.save(new LocationTree(paco, manila));
        locationTreeService.save(new LocationTree(pandacan, manila));
        locationTreeService.save(new LocationTree(port_area, manila));
        locationTreeService.save(new LocationTree(quiapo, manila));
        locationTreeService.save(new LocationTree(sampaloc, manila));
        locationTreeService.save(new LocationTree(san_andres, manila));
        locationTreeService.save(new LocationTree(san_miguel, manila));
        locationTreeService.save(new LocationTree(san_nicolas, manila));
        locationTreeService.save(new LocationTree(santa_ana, manila));
        locationTreeService.save(new LocationTree(santa_cruz, manila));
        locationTreeService.save(new LocationTree(santa_mesa, manila));
        locationTreeService.save(new LocationTree(tondo, manila));
        locationTreeService.save(new LocationTree(barangka, marikina));
        locationTreeService.save(new LocationTree(calumpang, marikina));
        locationTreeService.save(new LocationTree(concepcion_i_ii, marikina));
        locationTreeService.save(new LocationTree(fortune, marikina));
        locationTreeService.save(new LocationTree(industrial_valley, marikina));
        locationTreeService.save(new LocationTree(malanday, marikina));
        locationTreeService.save(new LocationTree(marikina_heights, marikina));
        locationTreeService.save(new LocationTree(nangka, marikina));
        locationTreeService.save(new LocationTree(parang, marikina));
        locationTreeService.save(new LocationTree(san_roque, marikina));
        locationTreeService.save(new LocationTree(santa_elena, marikina));
        locationTreeService.save(new LocationTree(santo_niño, marikina));
        locationTreeService.save(new LocationTree(tañong, marikina));
        locationTreeService.save(new LocationTree(tumana, marikina));
        locationTreeService.save(new LocationTree(alabang, muntinlupa));
        locationTreeService.save(new LocationTree(ayala_alabang, muntinlupa));
        locationTreeService.save(new LocationTree(bayanan, muntinlupa));
        locationTreeService.save(new LocationTree(buli, muntinlupa));
        locationTreeService.save(new LocationTree(cupang, muntinlupa));
        locationTreeService.save(new LocationTree(poblacion, muntinlupa));
        locationTreeService.save(new LocationTree(putatan, muntinlupa));
        locationTreeService.save(new LocationTree(sucat, muntinlupa));
        locationTreeService.save(new LocationTree(tunasan, muntinlupa));
        locationTreeService.save(new LocationTree(bagumbayan_north, navotas));
        locationTreeService.save(new LocationTree(bagumbayan_south, navotas));
        locationTreeService.save(new LocationTree(bangkulasi, navotas));
        locationTreeService.save(new LocationTree(daanghari, navotas));
        locationTreeService.save(new LocationTree(navotas_east, navotas));
        locationTreeService.save(new LocationTree(navotas_west, navotas));
        locationTreeService.save(new LocationTree(northbay_boulevard_north, navotas));
        locationTreeService.save(new LocationTree(northbay_boulevard_south, navotas));
        locationTreeService.save(new LocationTree(northbay_boulevard_south_1, navotas));
        locationTreeService.save(new LocationTree(northbay_boulevard_south_2, navotas));
        locationTreeService.save(new LocationTree(northbay_boulevard_south_3, navotas));
        locationTreeService.save(new LocationTree(san_jose, navotas));
        locationTreeService.save(new LocationTree(san_rafael_village, navotas));
        locationTreeService.save(new LocationTree(san_roque, navotas));
        locationTreeService.save(new LocationTree(sipac_almacen, navotas));
        locationTreeService.save(new LocationTree(tangos_north, navotas));
        locationTreeService.save(new LocationTree(tangos_south, navotas));
        locationTreeService.save(new LocationTree(tanza, navotas));
        locationTreeService.save(new LocationTree(baclaran, parañaque));
        locationTreeService.save(new LocationTree(bf_homes, parañaque));
        locationTreeService.save(new LocationTree(don_bosco, parañaque));
        locationTreeService.save(new LocationTree(don_galo, parañaque));
        locationTreeService.save(new LocationTree(la_huerta, parañaque));
        locationTreeService.save(new LocationTree(marcelo_green, parañaque));
        locationTreeService.save(new LocationTree(merville, parañaque));
        locationTreeService.save(new LocationTree(moonwalk, parañaque));
        locationTreeService.save(new LocationTree(san_antonio, parañaque));
        locationTreeService.save(new LocationTree(san_dionisio, parañaque));
        locationTreeService.save(new LocationTree(san_martin_de_porres, parañaque));
        locationTreeService.save(new LocationTree(santo_niño, parañaque));
        locationTreeService.save(new LocationTree(sun_valley, parañaque));
        locationTreeService.save(new LocationTree(tambo, parañaque));
        locationTreeService.save(new LocationTree(vitalez, parañaque));
        locationTreeService.save(new LocationTree(malibay, pasay));
        locationTreeService.save(new LocationTree(manila_bay_reclamation, pasay));
        locationTreeService.save(new LocationTree(maricaban, pasay));
        locationTreeService.save(new LocationTree(picc, pasay));
        locationTreeService.save(new LocationTree(san_isidro, pasay));
        locationTreeService.save(new LocationTree(san_jose, pasay));
        locationTreeService.save(new LocationTree(san_rafael, pasay));
        locationTreeService.save(new LocationTree(san_roque, pasay));
        locationTreeService.save(new LocationTree(santa_clara, pasay));
        locationTreeService.save(new LocationTree(santo_niño, pasay));
        locationTreeService.save(new LocationTree(villamor_airbase, pasay));
        locationTreeService.save(new LocationTree(bagong_ilog, pasig));
        locationTreeService.save(new LocationTree(bagong_katipunan, pasig));
        locationTreeService.save(new LocationTree(bambang, pasig));
        locationTreeService.save(new LocationTree(buting, pasig));
        locationTreeService.save(new LocationTree(caniogan, pasig));
        locationTreeService.save(new LocationTree(dela_paz, pasig));
        locationTreeService.save(new LocationTree(kalawaan, pasig));
        locationTreeService.save(new LocationTree(kapasigan, pasig));
        locationTreeService.save(new LocationTree(kapitolyo, pasig));
        locationTreeService.save(new LocationTree(malinao, pasig));
        locationTreeService.save(new LocationTree(manggahan, pasig));
        locationTreeService.save(new LocationTree(mauway, pasig));
        locationTreeService.save(new LocationTree(maybunga, pasig));
        locationTreeService.save(new LocationTree(oranbo, pasig));
        locationTreeService.save(new LocationTree(palatiw, pasig));
        locationTreeService.save(new LocationTree(pinagbuhatan, pasig));
        locationTreeService.save(new LocationTree(pineda, pasig));
        locationTreeService.save(new LocationTree(rosario, pasig));
        locationTreeService.save(new LocationTree(sagad, pasig));
        locationTreeService.save(new LocationTree(san_antonio, pasig));
        locationTreeService.save(new LocationTree(san_joaquin, pasig));
        locationTreeService.save(new LocationTree(san_jose, pasig));
        locationTreeService.save(new LocationTree(san_miguel, pasig));
        locationTreeService.save(new LocationTree(san_nicolas, pasig));
        locationTreeService.save(new LocationTree(santa_cruz, pasig));
        locationTreeService.save(new LocationTree(santa_lucia, pasig));
        locationTreeService.save(new LocationTree(santa_rosa, pasig));
        locationTreeService.save(new LocationTree(santo_tomas, pasig));
        locationTreeService.save(new LocationTree(santolan, pasig));
        locationTreeService.save(new LocationTree(sumilang, pasig));
        locationTreeService.save(new LocationTree(ugong, pasig));
        locationTreeService.save(new LocationTree(aguho, pateros));
        locationTreeService.save(new LocationTree(magtanggol, pateros));
        locationTreeService.save(new LocationTree(martires, pateros));
        locationTreeService.save(new LocationTree(poblacion, pateros));
        locationTreeService.save(new LocationTree(san_pedro, pateros));
        locationTreeService.save(new LocationTree(san_roque, pateros));
        locationTreeService.save(new LocationTree(santa_ana, pateros));
        locationTreeService.save(new LocationTree(santo_rosario_kanluran, pateros));
        locationTreeService.save(new LocationTree(santo_rosario_silangan, pateros));
        locationTreeService.save(new LocationTree(tabacalera, pateros));
        locationTreeService.save(new LocationTree(alicia, quezon_city));
        locationTreeService.save(new LocationTree(amihan, quezon_city));
        locationTreeService.save(new LocationTree(apolonio_samson, quezon_city));
        locationTreeService.save(new LocationTree(baesa, quezon_city));
        locationTreeService.save(new LocationTree(bagbag, quezon_city));
        locationTreeService.save(new LocationTree(bagong_lipunan_ng_crame, quezon_city));
        locationTreeService.save(new LocationTree(bagong_pag_asa, quezon_city));
        locationTreeService.save(new LocationTree(bagong_silangan, quezon_city));
        locationTreeService.save(new LocationTree(bagumbayan, quezon_city));
        locationTreeService.save(new LocationTree(bagumbuhay, quezon_city));
        locationTreeService.save(new LocationTree(bahay_toro, quezon_city));
        locationTreeService.save(new LocationTree(balingasa, quezon_city));
        locationTreeService.save(new LocationTree(balonbato, quezon_city));
        locationTreeService.save(new LocationTree(batasan_hills, quezon_city));
        locationTreeService.save(new LocationTree(bayanihan, quezon_city));
        locationTreeService.save(new LocationTree(blue_ridge_a_b, quezon_city));
        locationTreeService.save(new LocationTree(botocan, quezon_city));
        locationTreeService.save(new LocationTree(bungad, quezon_city));
        locationTreeService.save(new LocationTree(camp_aguinaldo, quezon_city));
        locationTreeService.save(new LocationTree(capri, quezon_city));
        locationTreeService.save(new LocationTree(central, quezon_city));
        locationTreeService.save(new LocationTree(commonwealth, quezon_city));
        locationTreeService.save(new LocationTree(culiat, quezon_city));
        locationTreeService.save(new LocationTree(damar, quezon_city));
        locationTreeService.save(new LocationTree(damayang_lagi, quezon_city));
        locationTreeService.save(new LocationTree(del_monte, quezon_city));
        locationTreeService.save(new LocationTree(dioquino_zobel, quezon_city));
        locationTreeService.save(new LocationTree(don_manuel, quezon_city));
        locationTreeService.save(new LocationTree(doña_aurora, quezon_city));
        locationTreeService.save(new LocationTree(doña_imelda, quezon_city));
        locationTreeService.save(new LocationTree(doña_josefa, quezon_city));
        locationTreeService.save(new LocationTree(duyan_duyan, quezon_city));
        locationTreeService.save(new LocationTree(e_rodriguez, quezon_city));
        locationTreeService.save(new LocationTree(east_kamias, quezon_city));
        locationTreeService.save(new LocationTree(escopa_i_iv, quezon_city));
        locationTreeService.save(new LocationTree(fairview, quezon_city));
        locationTreeService.save(new LocationTree(greater_lagro, quezon_city));
        locationTreeService.save(new LocationTree(gulod, quezon_city));
        locationTreeService.save(new LocationTree(holy_spirit, quezon_city));
        locationTreeService.save(new LocationTree(horseshoe, quezon_city));
        locationTreeService.save(new LocationTree(immaculate_concepcion, quezon_city));
        locationTreeService.save(new LocationTree(kaligayahan, quezon_city));
        locationTreeService.save(new LocationTree(kalusugan, quezon_city));
        locationTreeService.save(new LocationTree(kamuning, quezon_city));
        locationTreeService.save(new LocationTree(katipunan, quezon_city));
        locationTreeService.save(new LocationTree(kaunlaran, quezon_city));
        locationTreeService.save(new LocationTree(kristong_hari, quezon_city));
        locationTreeService.save(new LocationTree(krus_na_ligas, quezon_city));
        locationTreeService.save(new LocationTree(laging_handa, quezon_city));
        locationTreeService.save(new LocationTree(libis, quezon_city));
        locationTreeService.save(new LocationTree(lourdes, quezon_city));
        locationTreeService.save(new LocationTree(loyola_heights, quezon_city));
        locationTreeService.save(new LocationTree(maharlika, quezon_city));
        locationTreeService.save(new LocationTree(malaya, quezon_city));
        locationTreeService.save(new LocationTree(mangga, quezon_city));
        locationTreeService.save(new LocationTree(manresa, quezon_city));
        locationTreeService.save(new LocationTree(mariana, quezon_city));
        locationTreeService.save(new LocationTree(mariblo, quezon_city));
        locationTreeService.save(new LocationTree(marilag, quezon_city));
        locationTreeService.save(new LocationTree(masagana, quezon_city));
        locationTreeService.save(new LocationTree(masambong, quezon_city));
        locationTreeService.save(new LocationTree(matandang_balara, quezon_city));
        locationTreeService.save(new LocationTree(milagrosa, quezon_city));
        locationTreeService.save(new LocationTree(ns_amoranto, quezon_city));
        locationTreeService.save(new LocationTree(nagkaisang_nayon, quezon_city));
        locationTreeService.save(new LocationTree(nayong_kanluran, quezon_city));
        locationTreeService.save(new LocationTree(new_era, quezon_city));
        locationTreeService.save(new LocationTree(north_fairview, quezon_city));
        locationTreeService.save(new LocationTree(novaliches, quezon_city));
        locationTreeService.save(new LocationTree(obrero, quezon_city));
        locationTreeService.save(new LocationTree(old_capitol_site, quezon_city));
        locationTreeService.save(new LocationTree(paang_bundok, quezon_city));
        locationTreeService.save(new LocationTree(pag_ibig_sa_nayon, quezon_city));
        locationTreeService.save(new LocationTree(paligsahan, quezon_city));
        locationTreeService.save(new LocationTree(paltok, quezon_city));
        locationTreeService.save(new LocationTree(pansol, quezon_city));
        locationTreeService.save(new LocationTree(paraiso, quezon_city));
        locationTreeService.save(new LocationTree(pasong_putik, quezon_city));
        locationTreeService.save(new LocationTree(pasong_tamo, quezon_city));
        locationTreeService.save(new LocationTree(payatas, quezon_city));
        locationTreeService.save(new LocationTree(phil_am, quezon_city));
        locationTreeService.save(new LocationTree(pinagkaisahan, quezon_city));
        locationTreeService.save(new LocationTree(pinyahan, quezon_city));
        locationTreeService.save(new LocationTree(project_6, quezon_city));
        locationTreeService.save(new LocationTree(quirino_2_a_c, quezon_city));
        locationTreeService.save(new LocationTree(quirino_3_a_b, quezon_city));
        locationTreeService.save(new LocationTree(roxas, quezon_city));
        locationTreeService.save(new LocationTree(sacred_heart, quezon_city));
        locationTreeService.save(new LocationTree(salvacion, quezon_city));
        locationTreeService.save(new LocationTree(san_agustin, quezon_city));
        locationTreeService.save(new LocationTree(san_antonio, quezon_city));
        locationTreeService.save(new LocationTree(san_bartolome, quezon_city));
        locationTreeService.save(new LocationTree(san_isidro_galas, quezon_city));
        locationTreeService.save(new LocationTree(san_isidro_labrador, quezon_city));
        locationTreeService.save(new LocationTree(san_jose, quezon_city));
        locationTreeService.save(new LocationTree(san_martin_de_porres, quezon_city));
        locationTreeService.save(new LocationTree(san_roque, quezon_city));
        locationTreeService.save(new LocationTree(san_vicente, quezon_city));
        locationTreeService.save(new LocationTree(sangandaan, quezon_city));
        locationTreeService.save(new LocationTree(santa_cruz, quezon_city));
        locationTreeService.save(new LocationTree(santa_lucia, quezon_city));
        locationTreeService.save(new LocationTree(santa_monica, quezon_city));
        locationTreeService.save(new LocationTree(santa_teresita, quezon_city));
        locationTreeService.save(new LocationTree(santo_cristo, quezon_city));
        locationTreeService.save(new LocationTree(santo_domingo, quezon_city));
        locationTreeService.save(new LocationTree(santo_niño, quezon_city));
        locationTreeService.save(new LocationTree(santol, quezon_city));
        locationTreeService.save(new LocationTree(sauyo, quezon_city));
        locationTreeService.save(new LocationTree(siena, quezon_city));
        locationTreeService.save(new LocationTree(sikatuna_village, quezon_city));
        locationTreeService.save(new LocationTree(silangan, quezon_city));
        locationTreeService.save(new LocationTree(socorro_cubao, quezon_city));
        locationTreeService.save(new LocationTree(st_ignatius, quezon_city));
        locationTreeService.save(new LocationTree(st_peter, quezon_city));
        locationTreeService.save(new LocationTree(tagumpay, quezon_city));
        locationTreeService.save(new LocationTree(talayan, quezon_city));
        locationTreeService.save(new LocationTree(talipapa, quezon_city));
        locationTreeService.save(new LocationTree(tandang_sora, quezon_city));
        locationTreeService.save(new LocationTree(tatalon, quezon_city));
        locationTreeService.save(new LocationTree(teachers_village, quezon_city));
        locationTreeService.save(new LocationTree(ugong_norte, quezon_city));
        locationTreeService.save(new LocationTree(unang_sigaw, quezon_city));
        locationTreeService.save(new LocationTree(up_campus, quezon_city));
        locationTreeService.save(new LocationTree(up_village, quezon_city));
        locationTreeService.save(new LocationTree(valencia, quezon_city));
        locationTreeService.save(new LocationTree(vasra, quezon_city));
        locationTreeService.save(new LocationTree(veterans_village, quezon_city));
        locationTreeService.save(new LocationTree(villa_maria_clara, quezon_city));
        locationTreeService.save(new LocationTree(west_kamias, quezon_city));
        locationTreeService.save(new LocationTree(west_triangle, quezon_city));
        locationTreeService.save(new LocationTree(white_plains, quezon_city));
        locationTreeService.save(new LocationTree(addition_hills, san_juan));
        locationTreeService.save(new LocationTree(balong_bato, san_juan));
        locationTreeService.save(new LocationTree(batis, san_juan));
        locationTreeService.save(new LocationTree(corazon_de_jesus, san_juan));
        locationTreeService.save(new LocationTree(ermitaño, san_juan));
        locationTreeService.save(new LocationTree(greenhills, san_juan));
        locationTreeService.save(new LocationTree(isabelita, san_juan));
        locationTreeService.save(new LocationTree(kabayanan, san_juan));
        locationTreeService.save(new LocationTree(little_baguio, san_juan));
        locationTreeService.save(new LocationTree(maytunas, san_juan));
        locationTreeService.save(new LocationTree(onse, san_juan));
        locationTreeService.save(new LocationTree(pasadena, san_juan));
        locationTreeService.save(new LocationTree(pedro_cruz, san_juan));
        locationTreeService.save(new LocationTree(progreso, san_juan));
        locationTreeService.save(new LocationTree(rivera, san_juan));
        locationTreeService.save(new LocationTree(salapan, san_juan));
        locationTreeService.save(new LocationTree(san_perfecto, san_juan));
        locationTreeService.save(new LocationTree(santa_lucia, san_juan));
        locationTreeService.save(new LocationTree(st_joseph, san_juan));
        locationTreeService.save(new LocationTree(tibagan, san_juan));
        locationTreeService.save(new LocationTree(west_crame, san_juan));
        locationTreeService.save(new LocationTree(bagumbayan, taguig));
        locationTreeService.save(new LocationTree(bambang, taguig));
        locationTreeService.save(new LocationTree(calzada, taguig));
        locationTreeService.save(new LocationTree(central_bicutan, taguig));
        locationTreeService.save(new LocationTree(central_signal_village, taguig));
        locationTreeService.save(new LocationTree(fort_bonifacio, taguig));
        locationTreeService.save(new LocationTree(hagonoy, taguig));
        locationTreeService.save(new LocationTree(ibayo_tipas, taguig));
        locationTreeService.save(new LocationTree(katuparan, taguig));
        locationTreeService.save(new LocationTree(ligid_tipas, taguig));
        locationTreeService.save(new LocationTree(lower_bicutan, taguig));
        locationTreeService.save(new LocationTree(maharlika_village, taguig));
        locationTreeService.save(new LocationTree(napindan, taguig));
        locationTreeService.save(new LocationTree(new_lower_bicutan, taguig));
        locationTreeService.save(new LocationTree(north_daang_hari, taguig));
        locationTreeService.save(new LocationTree(north_signal_village, taguig));
        locationTreeService.save(new LocationTree(palingon, taguig));
        locationTreeService.save(new LocationTree(pinagsama, taguig));
        locationTreeService.save(new LocationTree(san_miguel, taguig));
        locationTreeService.save(new LocationTree(santa_ana, taguig));
        locationTreeService.save(new LocationTree(south_daang_hari, taguig));
        locationTreeService.save(new LocationTree(south_signal_village, taguig));
        locationTreeService.save(new LocationTree(tanyag, taguig));
        locationTreeService.save(new LocationTree(tuktukan, taguig));
        locationTreeService.save(new LocationTree(upper_bicutan, taguig));
        locationTreeService.save(new LocationTree(ususan, taguig));
        locationTreeService.save(new LocationTree(wawa, taguig));
        locationTreeService.save(new LocationTree(western_bicutan, taguig));
        locationTreeService.save(new LocationTree(arkong_bato, valenzuela_city));
        locationTreeService.save(new LocationTree(bagbaguin, valenzuela_city));
        locationTreeService.save(new LocationTree(balangkas, valenzuela_city));
        locationTreeService.save(new LocationTree(bignay, valenzuela_city));
        locationTreeService.save(new LocationTree(bisig, valenzuela_city));
        locationTreeService.save(new LocationTree(canumay, valenzuela_city));
        locationTreeService.save(new LocationTree(coloong, valenzuela_city));
        locationTreeService.save(new LocationTree(dalandanan, valenzuela_city));
        locationTreeService.save(new LocationTree(general_t_de_leon, valenzuela_city));
        locationTreeService.save(new LocationTree(isla, valenzuela_city));
        locationTreeService.save(new LocationTree(karuhatan, valenzuela_city));
        locationTreeService.save(new LocationTree(lawang_bato, valenzuela_city));
        locationTreeService.save(new LocationTree(lingunan, valenzuela_city));
        locationTreeService.save(new LocationTree(mabolo, valenzuela_city));
        locationTreeService.save(new LocationTree(malanday, valenzuela_city));
        locationTreeService.save(new LocationTree(malinta, valenzuela_city));
        locationTreeService.save(new LocationTree(mapulang_lupa, valenzuela_city));
        locationTreeService.save(new LocationTree(marulas, valenzuela_city));
        locationTreeService.save(new LocationTree(maysan, valenzuela_city));
        locationTreeService.save(new LocationTree(palasan, valenzuela_city));
        locationTreeService.save(new LocationTree(parada, valenzuela_city));
        locationTreeService.save(new LocationTree(pariancillo_villa, valenzuela_city));
        locationTreeService.save(new LocationTree(paso_de_blas, valenzuela_city));
        locationTreeService.save(new LocationTree(pasolo, valenzuela_city));
        locationTreeService.save(new LocationTree(poblacion, valenzuela_city));
        locationTreeService.save(new LocationTree(polo, valenzuela_city));
        locationTreeService.save(new LocationTree(punturin, valenzuela_city));
        locationTreeService.save(new LocationTree(rincon, valenzuela_city));
        locationTreeService.save(new LocationTree(tagalag, valenzuela_city));
        locationTreeService.save(new LocationTree(ugong, valenzuela_city));
        locationTreeService.save(new LocationTree(veinte_reales, valenzuela_city));
        locationTreeService.save(new LocationTree(bagong_silang, caloocan));
        locationTreeService.save(new LocationTree(camarin, caloocan));

        Customer magnum_talayan = new Customer("MAGNUM TALAYAN", CustomerType.CASHIER);
        magnum_talayan.setAddress("MARIA CLARA");
        magnum_talayan.setBarangay(talayan);
        magnum_talayan.setCity(quezon_city);
        magnum_talayan.setProvince(metro_manila);
        customerService.save(magnum_talayan);

        Customer magnum_edsa = new Customer("MAGNUM EDSA", CustomerType.CASHIER);
        magnum_edsa.setAddress("48 HOWMART RD.");
        magnum_edsa.setBarangay(apolonio_samson);
        magnum_edsa.setCity(quezon_city);
        magnum_edsa.setProvince(metro_manila);
        customerService.save(magnum_edsa);

        Customer marina = new Customer("MARINA SALES", CustomerType.VENDOR);
        marina.setAddress("HOWMART RD.");
        marina.setBarangay(apolonio_samson);
        marina.setCity(quezon_city);
        marina.setProvince(metro_manila);
        customerService.save(marina);

        Customer sarisari = new Customer("SARI SARI", CustomerType.OUTLET);
        sarisari.setAddress("123 DAANAN ST.");
        sarisari.setBarangay(guadalupe_nuevo);
        sarisari.setCity(makati);
        sarisari.setProvince(metro_manila);
        sarisari.setChannel(channelService.get(2));
        sarisari.setVisitFrequency(VisitFrequency.F2);
        sarisari.setRouteHistory(Arrays.asList(new Routing(sarisari, s41, startDate)));
        customerService.save(sarisari);

        Customer palengke = new Customer("TALIPAPA", CustomerType.OUTLET);
        palengke.setAddress("456 TALIPAPAAN ST.");
        palengke.setBarangay(apolonio_samson);
        palengke.setCity(quezon_city);
        palengke.setProvince(metro_manila);
        palengke.setChannel(channelService.get(3));
        palengke.setVisitFrequency(VisitFrequency.F4);
        palengke.setRouteHistory(Arrays.asList(new Routing(palengke, pms1, startDate)));
        customerService.save(palengke);

        Customer variety = new Customer("VARIETY", CustomerType.OUTLET);
        variety.setAddress("ROAD 789");
        variety.setBarangay(guadalupe_viejo);
        variety.setCity(makati);
        variety.setProvince(metro_manila);
        variety.setChannel(channelService.get(2));
        variety.setVisitFrequency(VisitFrequency.F2);
        variety.setRouteHistory(Arrays.asList(new Routing(variety, s42, startDate)));
        customerService.save(variety);

        Customer wetStall = new Customer("WET MARKET STALL", CustomerType.OUTLET);
        wetStall.setAddress("STALL 1, GALAS MARKET");
        wetStall.setBarangay(san_isidro_galas);
        wetStall.setCity(quezon_city);
        wetStall.setProvince(metro_manila);
        wetStall.setChannel(channelService.get(3));
        wetStall.setVisitFrequency(VisitFrequency.F4);
        wetStall.setRouteHistory(Arrays.asList(new Routing(wetStall, pms2, startDate)));
        customerService.save(wetStall);

        Customer dryStall = new Customer("DRY MARKET STALL", CustomerType.OUTLET);
        dryStall.setAddress("STALL 2, GALAS MARKET");
        dryStall.setBarangay(san_isidro_galas);
        dryStall.setCity(quezon_city);
        dryStall.setProvince(metro_manila);
        dryStall.setChannel(channelService.get(4));
        dryStall.setVisitFrequency(VisitFrequency.F4);
        dryStall.setRouteHistory(Arrays.asList(new Routing(dryStall, pms3, startDate)));
        customerService.save(dryStall);
    }
}
